apiVersion: 1

groups:
  - name: TestAlerts
    interval: 1m
    rules:
      - uid: high-cpu
        title: High CPU Usage
        condition: C
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: avg(rate(node_cpu_seconds_total{mode="system"}[1m])) * 100
              interval: ""
              legendFormat: CPU Usage
              instant: false
        noDataState: Alerting
        execErrState: Alerting
        for: 1m
        annotations:
          summary: "CPU usage > 60%"
          description: "System CPU usage has crossed 60% for more than 1 minute."
        labels:
          severity: warning
