apiVersion: 1

groups:
  - name: CPU_Usage_Alerts
    folder: "Custom Alerts V2"
    interval: 10s
    rules:
      - uid: cpu-alert
        title: CPU Usage High
        condition: D
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              expr: node_cpu_seconds_total
              instant: false
              format: time_series
              intervalMs: 15000
              interval: ""
              legendFormat: ""
              step: 15
          - refId: B
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              expr: (1 - avg(rate(node_cpu_seconds_total{mode="idle"}[1m]))) * 100
              instant: false
              format: time_series
              intervalMs: 15000
              interval: ""
              legendFormat: ""
              step: 15
          - refId: C
            datasourceUid: __expr__
            model:
              type: reduce
              expression: B
              reducer: avg
              settings:
                mode: mean
          - refId: D
            datasourceUid: __expr__
            model:
              type: threshold
              expression: C
              conditions:
                - evaluator:
                    params:
                      - 80
                    type: gt
                  operator:
                    type: and
                  reducer:
                    type: avg

